// Code generated by goctl. DO NOT EDIT.
package types

type BusinessListReq struct {
	LastId             int64 `json:"lastId"`             // ID of the last item fetched
	PageSize           int64 `json:"pageSize"`           // Number of items to fetch
	HomestayBusinessId int64 `json:"homestayBusinessId"` // Store ID to filter by
}

type BusinessListResp struct {
	List []Homestay `json:"list"` // List of homestays
}

type CommentListReq struct {
	LastId   int64 `json:"lastId"`   // ID of the last comment fetched
	PageSize int64 `json:"pageSize"` // Number of comments to fetch
}

type CommentListResp struct {
	List []HomestayComment `json:"list"` // List of comments
}

type GoodBossReq struct {
}

type GoodBossResp struct {
	List []HomestayBusinessBoss `json:"list"` // List of homestay business bosses
}

type GuessListReq struct {
}

type GuessListResp struct {
	List []Homestay `json:"list"` // List of guessed homestays
}

type Homestay struct {
	Id                  int64   `json:"id"`
	Title               string  `json:"title"`
	SubTitle            string  `json:"subTitle"`
	Banner              string  `json:"banner"`
	Info                string  `json:"info"`
	PeopleNum           int64   `json:"peopleNum"`           // Number of people the homestay can accommodate
	HomestayBusinessId  int64   `json:"homestayBusinessId"`  // Store ID
	UserId              int64   `json:"userId"`              // Host ID
	RowState            int64   `json:"rowState"`            // 0: Inactive, 1: Active
	RowType             int64   `json:"rowType"`             // Selling type 0: by room, 1: by person
	FoodInfo            string  `json:"foodInfo"`            // Meal standards
	FoodPrice           float64 `json:"foodPrice"`           // Meal price
	HomestayPrice       float64 `json:"homestayPrice"`       // Homestay price
	MarketHomestayPrice float64 `json:"marketHomestayPrice"` // Market price of the homestay
}

type HomestayBusiness struct {
	Id        int64   `json:"id"`
	Title     string  `json:"title"`     // Store name
	Info      string  `json:"info"`      // Store introduction
	Tags      string  `json:"tags"`      // Tags, separated by ','
	Cover     string  `json:"cover"`     // Cover image
	Star      float64 `json:"star"`      // Star rating
	IsFav     int64   `json:"isFav"`     // Is favorite
	HeaderImg string  `json:"headerImg"` // Storefront image
}

type HomestayBusinessBoss struct {
	Id       int64  `json:"id"`
	UserId   int64  `json:"userId"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"` // Introduction of the homestay owner
	Rank     int64  `json:"rank"` // Ranking
}

type HomestayBusinessListInfo struct {
	HomestayBusiness
	SellMonth     int64 `json:"sellMonth"`     // Monthly sales
	PersonConsume int64 `json:"personConsume"` // Personal consumption
}

type HomestayBussinessDetailReq struct {
	Id int64 `json:"id"` // ID of the homestay business
}

type HomestayBussinessDetailResp struct {
	Boss HomestayBusinessBoss `json:"boss"` // Detailed information of the business boss
}

type HomestayBussinessListReq struct {
	LastId   int64 `json:"lastId"`   // ID of the last item fetched
	PageSize int64 `json:"pageSize"` // Number of items to fetch
}

type HomestayBussinessListResp struct {
	List []HomestayBusinessListInfo `json:"list"` // List of homestay businesses with additional info
}

type HomestayComment struct {
	Id         int64   `json:"id"`
	HomestayId int64   `json:"homestayId"` // ID of the homestay associated with the comment
	Content    string  `json:"content"`    // Content of the comment
	Star       float64 `json:"star"`       // Star rating given in the comment
	UserId     int64   `json:"userId"`     // ID of the user who made the comment
	Nickname   string  `json:"nickname"`   // Nickname of the user
	Avatar     string  `json:"avatar"`     // Avatar of the user
}

type HomestayDetailReq struct {
	Id int64 `json:"id"` // ID of the homestay
}

type HomestayDetailResp struct {
	Homestay Homestay `json:"homestay"` // Detailed information of a homestay
}

type HomestayListReq struct {
	Page     int64 `json:"page"`     // Page number
	PageSize int64 `json:"pageSize"` // Number of items per page
}

type HomestayListResp struct {
	List []Homestay `json:"list"` // List of homestays
}
