// Code generated by goctl. DO NOT EDIT.
package types

type CreateHomestayOrderReq struct {
	HomestayId    int64  `json:"homestayId"`
	IsFood        bool   `json:"isFood"`
	LiveStartTime int64  `json:"liveStartTime"`
	LiveEndTime   int64  `json:"liveEndTime"`
	LivePeopleNum int64  `json:"livePeopleNum"`
	Remark        string `json:"remark"`
}

type CreateHomestayOrderResp struct {
	OrderSn string `json:"orderSn"`
}

type UserHomestayOrderDetailReq struct {
	Sn string `json:"sn"`
}

type UserHomestayOrderDetailResp struct {
	Sn                  string  `json:"sn"`                  // Order number
	UserId              int64   `json:"userId"`              // User ID
	HomestayId          int64   `json:"homestayId"`          // Homestay ID
	Title               string  `json:"title"`               // Title
	SubTitle            string  `json:"subTitle"`            // Subtitle
	Cover               string  `json:"cover"`               // Cover
	Info                string  `json:"info"`                // Introduction
	FoodInfo            string  `json:"foodInfo"`            // Food standard
	FoodPrice           float64 `json:"foodPrice"`           // Food price (cents)
	HomestayPrice       float64 `json:"homestayPrice"`       // Homestay price (cents)
	MarketHomestayPrice float64 `json:"marketHomestayPrice"` // Homestay market price (cents)
	HomestayBusinessId  float64 `json:"homestayBusinessId"`  // Store ID
	HomestayUserId      float64 `json:"homestayUserId"`      // Store landlord ID
	OrderTotalPrice     float64 `json:"orderTotalPrice"`     // Total order price
	CreateTime          int64   `json:"createTime"`          // Order time
	TradeState          int64   `json:"tradeState"`          // -1: Canceled 0: To be paid 1: Unused 2: Used 3: Refunded 4: Expired
	LiveStartDate       int64   `json:"liveStartDate"`       // Check-in start date
	LiveEndDate         int64   `json:"liveEndDate"`         // Check-in end date
	TradeCode           string  `json:"tradeCode"`           // Transaction code
	FoodTotalPrice      float64 `json:"foodTotalPrice"`      // Total food price (cents)
	HomestayTotalPrice  float64 `json:"homestayTotalPrice"`  // Total homestay price (cents)
	Remark              string  `json:"remark"`              // Remarks
	LivePeopleNum       int64   `json:"livePeopleNum"`       // Actual number of people staying
	NeedFood            int64   `json:"needFood"`            // 0: No need for food 1: Need parameters
	PayTime             int64   `json:"payTime"`             // Payment time
	PayType             string  `json:"payType"`             // Payment type
}

type UserHomestayOrderListReq struct {
	LastId     int64 `json:"lastId"`
	PageSize   int64 `json:"pageSize"`
	TradeState int64 `json:"tradeState"` // -99: All 0: Pending payment orders 1: Valid orders
}

type UserHomestayOrderListResp struct {
	List []UserHomestayOrderListView `json:"list"`
}

type UserHomestayOrderListView struct {
	Sn              string  `json:"sn"`              // Order number
	Title           string  `json:"title"`           // Title
	SubTitle        string  `json:"subTitle"`        // Subtitle
	HomestayId      int64   `json:"homestayId"`      // Homestay ID
	Cover           string  `json:"cover"`           // Cover
	OrderTotalPrice float64 `json:"orderTotalPrice"` // Total order price
	CreateTime      int64   `json:"createTime"`      // Order time
	TradeState      int64   `json:"tradeState"`      // -1: Canceled 0: To be paid 1: Unused 2: Used 3: Refunded 4: Expired
	LiveStartDate   int64   `json:"liveStartDate"`   // Check-in start date
	LiveEndDate     int64   `json:"liveEndDate"`     // Check-in end date
	TradeCode       string  `json:"tradeCode"`       // Transaction code
}
